# It contains all the configs required in the project

data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip